/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Matt LM (https://sketchfab.com/Matt_LeMoine)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/models/b044c4def4f244138906aa78d52aa2fa
title: Asteroid
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSphere } from '@react-three/cannon'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/asteroid/scene.gltf')

  const [ref] = useSphere(() => ({
    mass: 1,
    angularVelocity: [Math.random() * 2 - 1, Math.random() * 2 - 1, Math.random() * 2 - 1],
  }))

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={props.rotation}>
        <group position={props.position}>
          <mesh ref={ref} geometry={nodes.mesh_0.geometry} scale={0.005} material={materials.Default} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/asteroid/scene.gltf')
