/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: _Vadim2020_ (https://sketchfab.com/Maha_Knox)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/x-wing-t65-cockpit-bbbed2d66c4e4601a91d3f109cac6968
title: X-Wing T65 Cockpit
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useAtom } from 'jotai'
import React, { useRef } from 'react'
import { cameraAtom } from '../store/gameAtoms'

export default function Cockpit({ ...props }) {
  const ref = useRef()
  const [camera] = useAtom(cameraAtom)

  useFrame(() => {
    // console.log({x, y, z})
    // ref.current.position.copy(camera.position)
    ref.current.position.set(camera.position.x + 10, camera.position.y + 10, camera.position.z + 10)
  })

  const { nodes, materials } = useGLTF('/cockpit/scene.gltf')
  return (
    <group ref={ref} {...props} scale={1} position={[0, 0, 0]}>
      <group position={[0, -0.92, 0]} rotation={[1.57, 0, 0]}>
        <group scale={0.01}>
          <mesh
            geometry={
              nodes.SM_MERGED_vehicle_air_xwing_t65_cockpit_cutscene_mesh_Window_shader_20_Heroship_Glass__0.geometry
            }
            material={materials.Heroship_Glass}
          />
          <mesh
            geometry={
              nodes
                .SM_MERGED_vehicle_air_xwing_t65_cockpit_cutscene_mesh_Window_shader_20_T_XWingCockpitScreen_01_C_Mat_0
                .geometry
            }
            material={materials.T_XWingCockpitScreen_01_C_Mat}
          />
          <mesh
            geometry={
              nodes.SM_MERGED_vehicle_air_xwing_t65_cockpit_cutscene_mesh_Window_shader_20_T_XWingCockpit_01_CS_Mat_0
                .geometry
            }
            material={materials.T_XWingCockpit_01_CS_Mat}
          />
          <mesh
            geometry={
              nodes
                .SM_MERGED_vehicle_air_xwing_t65_cockpit_cutscene_mesh_Window_shader_20_T_XWingCockpit_01_emissive_Mat_0
                .geometry
            }
            material={materials.T_XWingCockpit_01_emissive_Mat}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cockpit/scene.gltf')
