/* eslint-disable react/prop-types */
/*
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rakshaan (https://sketchfab.com/rakshaan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/assault-frigate-a39d5917f75e433fae7a95635578f228
title: Assault Frigate
*/

import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useAtom } from 'jotai'
import React, { useRef } from 'react'
import { clockAtom, frigatesAtom } from '../store/gameAtoms'

export default function Frigates() {
  const gltf = useGLTF('/assault_frigate/scene.gltf')
  const frigates = useAtom(frigatesAtom)

  const render = frigates[0].map(data => <Frigate {...gltf} key={data.guid} data={data} />)

  return <>{render}</>
}

const Frigate = React.memo(({ nodes, materials }) => {
  const ref = useRef()
  const [clock] = useAtom(clockAtom)
  useFrame(() => {
    // orbit the frigate

    const r = Math.cos((clock.getElapsedTime() / 2) * 0.1) * Math.PI
    ref.current.position.set(Math.cos(r) * 40, 0, Math.sin(r) * 40)
    // rotate as orbiting
    ref.current.rotation.set(r, r, 0)
  })
  return (
    <group ref={ref} dispose={null} position={[0, 0, 9]} scale={10}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <spotLight intensity={2} />
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  )
})

Frigate.displayName = 'Frigate'

useGLTF.preload('/assault_frigate/scene.gltf')
