/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: feivelyn (https://sketchfab.com/feivelyn)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/various-planets-73c6c24e7c40409cafc6adacd5d71ff5
title: Various Planets
*/

import { useSphere } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'

export default function Planet(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/various_planets/scene.gltf')
  // const { actions } = useAnimations(animations, group)

  const [ref] = useSphere(() => ({
    mass: 1,
    angularVelocity: [Math.random() * 0.2, Math.random() * 0.2, Math.random() * 0.2],
  }))

  return (
    <group ref={group} {...props} dispose={null} position={[-1000, -100, -100]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={props.position}>
            <mesh ref={ref} scale={100} geometry={nodes.Object_20.geometry} material={materials.Planet_barren} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/various_planets/scene.gltf')
