/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Axt (https://sketchfab.com/shooter24994)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/saturn-8fb67d3defd74aaa880df3a08317e641
title: Saturn
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RingedPlanet({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/saturn/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[1000, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group rotation={[-Math.PI / 2, 0.24, 0]} scale={[163.36, 163.36, 163.36]}>
            <mesh geometry={nodes.Circle_ring_0.geometry} material={materials.ring} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/saturn/scene.gltf')
